# Generated by Django 5.1.1 on 2024-09-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [models.Index(fields=["full_name"], name="tracker_emp_full_na_b2591c_idx")],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("deadline", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начата"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Завершена"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tracker.employee",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tracker.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "deadline"],
                        name="tracker_tas_status_a02a62_idx",
                    ),
                    models.Index(
                        fields=["assignee", "status"],
                        name="tracker_tas_assigne_454143_idx",
                    ),
                ],
            },
        ),
    ]
